# Generated by Django 2.1.7 on 2020-06-09 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_user_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='Log',
            field=models.ManyToManyField(to='Users.Message'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='Participant1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='Users.user'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='Participant2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='Users.user'),
        ),
    ]
