# Generated by Django 2.1.7 on 2020-04-21 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booklets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='بدون ذکر نام', max_length=100)),
                ('Category', models.CharField(choices=[('بدون دسته بندی', 'بدون دسته بندی'), ('پزشکی', 'پزشکی'), ('علوم پایه', 'علوم پایه'), ('زیست شناسی', 'زیست شناسی'), ('زمین شناسی', 'زمین شناسی'), ('مهندسی', 'منهدسی'), ('روانشناسی', 'روانشناسی'), ('حقوق', 'حقوق')], default='بدون دسته بندی', max_length=100)),
                ('Description', models.TextField(default='بدون توضیحات')),
                ('Course_name', models.CharField(default='بدون ذکر نام درس', max_length=100)),
                ('Price', models.CharField(default='بدون قیمت', max_length=100)),
                ('University_name', models.CharField(default='بدون ذکر نام دانشگاه', max_length=100)),
                ('Professor_name', models.CharField(default='بدون ذکر نام استاد', max_length=100)),
                ('Semester', models.CharField(default='بدون ذکر ترم', max_length=100)),
                ('تصویر جزوه', models.ImageField(blank=True, upload_to='BookLET/%Y/%m/%d/')),
                ('پی دی اف', models.FileField(blank=True, upload_to='BookLETPDF/%Y/%m/%d/')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book_let_owner', to='Users.user')),
            ],
        ),
    ]
