# Generated by Django 2.1.7 on 2020-04-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklets',
            old_name='تصویر جزوه',
            new_name='BookletIMG',
        ),
        migrations.RenameField(
            model_name='booklets',
            old_name='پی دی اف',
            new_name='PDF_FILE',
        ),
    ]
