# Generated by Django 2.1.7 on 2020-04-21 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0002_auto_20200421_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booklets',
            name='Price',
        ),
    ]
