# Generated by Django 2.1.7 on 2020-04-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0004_booklets_pdf_validate_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklets',
            name='Category',
            field=models.CharField(choices=[('بدون دسته بندی', 'بدون دسته بندی'), ('پزشکی', 'پزشکی'), ('علوم پایه', 'علوم پایه'), ('زیست شناسی', 'زیست شناسی'), ('زمین شناسی', 'زمین شناسی'), ('مهندسی', 'مهندسی'), ('روانشناسی', 'روانشناسی'), ('حقوق', 'حقوق')], default='بدون دسته بندی', max_length=100),
        ),
    ]
