# Generated by Django 2.1.7 on 2020-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0005_auto_20200429_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklets',
            name='University_name',
            field=models.CharField(blank=True, default='بدون ذکر نام دانشگاه', max_length=100),
        ),
    ]
