# Generated by Django 2.1.7 on 2020-05-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklets', '0006_auto_20200510_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklets',
            name='Category',
            field=models.CharField(blank=True, choices=[('بدون دسته بندی', 'بدون دسته بندی'), ('پزشکی', 'پزشکی'), ('علوم پایه', 'علوم پایه'), ('زیست شناسی', 'زیست شناسی'), ('زمین شناسی', 'زمین شناسی'), ('مهندسی', 'مهندسی'), ('روانشناسی', 'روانشناسی'), ('حقوق', 'حقوق')], default='بدون دسته بندی', max_length=100),
        ),
        migrations.AlterField(
            model_name='booklets',
            name='Course_name',
            field=models.CharField(blank=True, default='بدون ذکر نام درس', max_length=100),
        ),
        migrations.AlterField(
            model_name='booklets',
            name='Description',
            field=models.TextField(blank=True, default='بدون توضیحات'),
        ),
        migrations.AlterField(
            model_name='booklets',
            name='Professor_name',
            field=models.CharField(blank=True, default='بدون ذکر نام استاد', max_length=100),
        ),
        migrations.AlterField(
            model_name='booklets',
            name='Semester',
            field=models.CharField(blank=True, default='بدون ذکر ترم', max_length=100),
        ),
    ]
