# Generated by Django 2.1.7 on 2020-04-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0002_auto_20200407_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='بدون عنوان', max_length=100)),
                ('Description', models.TextField(default='بدون توضیحات')),
                ('Categories', models.CharField(choices=[('بدون دسته بندی', 'بدون دسته بندی'), ('ادبیات', 'ادبیات'), ('سفرنامه', 'سفرنامه'), ('رمان', 'رمان'), ('جغرافیا', 'جغرافیا'), ('کتاب مرجع', 'کتاب مرجع'), ('ورزشی', 'ورزشی'), ('حقوقی', 'حقوقی'), ('آشپزی', 'آشپزی'), ('روانشناسی', 'روانشناسی'), ('کتاب مصور', 'کتاب مصور'), ('تاریخی', 'تاریخی'), ('اجتماعی', 'اجتماعی')], default='بدون دسته بندی', max_length=100)),
                ('Publish_date', models.CharField(default='تاریخ ذکر نشده است', max_length=100)),
                ('Author', models.CharField(default='بدون نویسنده', max_length=100)),
                ('ISBN', models.CharField(default='بدون شابک', max_length=100)),
                ('Publisher', models.CharField(default='بدون ناشر', max_length=100)),
                ('BookIMG', models.ImageField(blank=True, upload_to='Image/%Y/%m/%d/')),
                ('کتاب الکترونیکی', models.FileField(blank=True, upload_to='PDF/%Y/%m/%d/')),
                ('کتاب صوتی', models.FileField(blank=True, upload_to='Audios/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.ManyToManyField(related_name='have_book', to='Users.user')),
                ('Proposed_book', models.ManyToManyField(related_name='proposedBook', to='books.Books')),
            ],
        ),
    ]
