# Generated by Django 2.1.7 on 2020-04-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='BookIMG2',
            field=models.ImageField(blank=True, upload_to='Image/%Y/%m/%d/'),
        ),
    ]
