# Generated by Django 2.1.7 on 2020-04-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposed_book',
            name='Owner',
        ),
        migrations.AddField(
            model_name='proposed_book',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='have_book', to='Users.user'),
        ),
        migrations.AlterField(
            model_name='proposed_book',
            name='Proposed_book',
            field=models.ManyToManyField(to='books.Books'),
        ),
    ]
