# Generated by Django 2.1.7 on 2020-04-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200414_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposed_book',
            name='Proposed_book',
        ),
        migrations.AddField(
            model_name='proposed_book',
            name='Proposed_book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposedBook', to='books.Books'),
        ),
    ]
