# Generated by Django 2.1.7 on 2020-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_bookimg2'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='Price',
            field=models.CharField(default='بدون قیمت', max_length=100),
        ),
        migrations.AddField(
            model_name='proposal_book',
            name='Descriptions',
            field=models.CharField(default='بدون توضیحات', max_length=100),
        ),
        migrations.AddField(
            model_name='proposal_book',
            name='Offered_price',
            field=models.CharField(default='بدون قیمت', max_length=100),
        ),
    ]
