# Generated by Django 2.1.7 on 2020-04-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('books', '0004_auto_20200414_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_rated', to='Users.user')),
            ],
        ),
    ]
