# Generated by Django 2.1.7 on 2020-04-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('books', '0005_leaderrate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaderRate',
            new_name='BookRate',
        ),
    ]
