# Generated by Django 2.1.7 on 2020-04-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_borrow_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow_book',
            name='EndBorrowingTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='borrow_book',
            name='StartBorrowingTime',
            field=models.DateTimeField(null=True),
        ),
    ]
