# Generated by Django 2.1.7 on 2020-04-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20200416_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='publish_series',
            field=models.CharField(blank=True, default=' ذکر نشده است', max_length=100),
        ),
    ]
