# Generated by Django 2.1.7 on 2020-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_books_publish_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='publish_series',
            field=models.CharField(default=' ذکر نشده است', max_length=100),
        ),
    ]
