# Generated by Django 2.1.7 on 2020-04-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20200418_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='کتاب صوتی',
            new_name='Audio_Book',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='کتاب الکترونیکی',
            new_name='PDF_Book',
        ),
    ]
