# Generated by Django 2.1.7 on 2020-05-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('books', '0012_auto_20200421_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WishedBook', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Books')),
                ('Wishers', models.ManyToManyField(blank=True, to='Users.user')),
            ],
        ),
    ]
