# Generated by Django 2.1.7 on 2020-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20200511_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposed_book',
            name='Proposed_book',
        ),
        migrations.AddField(
            model_name='proposed_book',
            name='Proposed_book',
            field=models.ManyToManyField(to='books.Books'),
        ),
    ]
