# Generated by Django 2.1.7 on 2020-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_auto_20200511_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposed_book',
            name='Offered_price',
            field=models.IntegerField(default=0),
        ),
    ]
