# Generated by Django 2.1.7 on 2020-06-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_auto_20200609_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='BComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Title', models.CharField(default='بدون عنوان', max_length=40)),
                ('Text', models.CharField(max_length=100)),
                ('Likes', models.IntegerField(default=0)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
        migrations.CreateModel(
            name='BPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Thumbnail', models.ImageField(blank=True, upload_to='Blog/thumbnails/%Y/%m/%d')),
                ('Title', models.CharField(max_length=40)),
                ('Text', models.TextField()),
                ('PostImage', models.ImageField(blank=True, upload_to='Blog/posts/%Y/%m/%d')),
                ('Likes', models.IntegerField(default=0)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
                ('Comments', models.ManyToManyField(to='Blog.BComment')),
            ],
        ),
    ]
