# Generated by Django 2.1.7 on 2020-04-22 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_auto_20200421_2010'),
        ('cart', '0004_cart_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='order_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Item_want_to_buy', to='books.Proposed_Book'),
        ),
    ]
