# Generated by Django 2.1.7 on 2020-04-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20200422_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Item_want_to_buy', to='books.Proposed_Book'),
        ),
    ]
