# Generated by Django 2.1.7 on 2020-04-15 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0006_auto_20200415_1732'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_Text', models.TextField(default='نظر کاربر')),
                ('Owners_HR', models.CharField(choices=[('0', 'bad'), ('1', 'medium'), ('2', 'good'), ('n/a', 'N/A')], default='n/a', max_length=8)),
                ('Addressed_Book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='books.Proposed_Book')),
                ('Comment_Author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
