# Generated by Django 2.1.7 on 2020-05-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20200416_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Comment_Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
        ),
    ]
